version: "3"

services:
  coach-bot:
    build: .
    image: coach-transcriber-bot:coach-bot
    # image: nvidia/cuda:10.2-base
    # command: nvidia-smi
    ports:
      - "3000:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              # count: 1
              capabilities: [gpu]
    volumes:
      - ./tmp:/tmp